### ISSUE TITLE
check UDP

### ISSUE THREAD

**Issue by d-a-v** [d-a-v/esp82xx-nonos-linklayer#14]
UDP packet size should be independent from MSS and limited only by MTU.
Needs testing
ref: [esp8266/Arduino#4539](https://github.com/esp8266/Arduino/pull/4539#discussion_r178637937)

**Comment by earlephilhower** [comment]
I think you're OK, it was a mistake on my part.  I've just retried with 1200 byte packets and it's OK.  I must have tried sending 1000 samples (which would be 4K bytes and which I imagine should not work)....

Sorry!

**Comment by d-a-v** [comment]
No problem, thanks !
