### ISSUE TITLE
Don't reset default route when something else had changed it

### ISSUE THREAD

**Issue by mcspr** [d-a-v/esp82xx-nonos-linklayer#52]
ref. <s>https://github.com/esp8266/Arduino/pull/7148</s> https://github.com/esp8266/Arduino/pull/8317

Current implementation resets default route regardless of it's contents:
https://github.com/d-a-v/esp82xx-nonos-linklayer/blob/18975ca6c4facb2d57de706bec0843f286b7b0e2/glue-lwip/lwip-git.c#L322-L326

But, it does respect un-setting it:
https://github.com/d-a-v/esp82xx-nonos-linklayer/blob/18975ca6c4facb2d57de706bec0843f286b7b0e2/glue-lwip/lwip-git.c#L525-L526

Should it respect the already-set netif?

```diff
diff --git a/glue-lwip/lwip-git.c b/glue-lwip/lwip-git.c
index 4cf133f..b3afc4d 100644
--- a/glue-lwip/lwip-git.c
+++ b/glue-lwip/lwip-git.c
@@ -322,8 +322,10 @@ static void netif_sta_status_callback (struct netif* netif)
        if (   netif->flags & NETIF_FLAG_UP
            && netif == netif_sta)
        {
-               // this is our default route
-               netif_set_default(netif);
+               // this is our default route, but only when there is nothing else
+               if (netif_default == NULL) {
+                       netif_set_default(netif);
+               }

                // If we have a valid address of any type restart SNTP
                bool valid_address = ip_2_ip4(&netif->ip_addr)->addr;
```

If yes, Core's Lwip class also needs a patch of the same nature

**Comment by d-a-v** [comment]
fixed by #54
https://github.com/d-a-v/esp82xx-nonos-linklayer/blob/450bb63c1bc8b35770ca7f246945cf383569f52f/glue-lwip/lwip-git.c#L325
