### ISSUE TITLE
Please change DNS max hostname length back to 256

### ISSUE THREAD

**Issue by Redferne** [d-a-v/esp82xx-nonos-linklayer#7]
Many IoT cloud services has insanely long hostnames, easy >64 chars.

https://github.com/d-a-v/esp82xx-nonos-linklayer/blob/693bfddbe274ade1b7aec731e8c688c073b976c5/glue-lwip/arduino/lwipopts.h#L1048

**Comment by d-a-v** [comment]
128 would do it ?

**Comment by Redferne** [comment]
For me yes. Currently seeing around 100 chars for some services running on Azure.

**Comment by d-a-v** [comment]
done in https://github.com/d-a-v/esp82xx-nonos-linklayer/commit/71591f9e8dcd07e10ae330493bceb310b3900d6c
